for each image row in input image:
   for each pixel in image row:

      set sum to zero

      for each convolution row in convolution:
         for each element in convolution row:

            if element position  corresponding* to pixel position then
               multiply element value  corresponding* to pixel value
               add result to sum
            endif

      set output image pixel to sum




In [0]:
import numpy as np

a = np.array([[3,1,1,2,8,4],[1,0,7,3,2,6],[2,3,5,1,1,3],[1,4,1,2,6,5],[3,2,1,3,7,2],[9,2,6,2,5,1]])

b = np.array([[1,0,-1],[1,0,-1],[1,0,-1]])

output = np.arange(16).reshape(4,4)

for i in range(4):
    for j in range(4):
        
        matrix_c = matrix_a[i:i+3, j:j+3] 
        temp = np.multiply(matrix_c, matrix_b)
        conv_sum = temp.sum()
        #print(conv_sum)
        output[i,j] = conv_sum

print(output[:,:])

[[ -7  -2   2  -7]
 [ -9   1   4  -8]
 [ -1   3  -7  -4]
 [  5   1 -10  -1]]
